# Generated by Django 2.2.11 on 2020-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
