# Generated by Django 2.2.11 on 2020-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=5000)),
                ('options', models.CharField(blank=True, default='', max_length=1000)),
                ('priority', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=5000),
        ),
    ]
